version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/aws-cicd-nodejs-app
hooks:
  ApplicationStop:
    - location: scriopt/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scriopt/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
